// curriculumSubjects.js

export const curriculumSubjects = {
    "JSS 1 GREY": [
        "Language Arts",
        "Mathematics",
        "Integrated Science",
        "Social Studies",
        "Agricultural Science",
        "Physical Health Education",
        "Religious and Moral Education",
        "French",
        "S.L Language(kerio)",
        "Business Studies",
        "Home Economics",
        "Basic Electronics",
        "Introductory Technology",
        "Creative Practical Art",
        "Performing Art",
        "Computer Studies",
        "Music",
    ],
    "JSS 1 WHITE": [
        "Language Arts",
        "Mathematics",
        "Integrated Science",
        "Social Studies",
        "Agricultural Science",
        "Physical Health Education",
        "Religious and Moral Education",
        "French",
        "S.L Language(kerio)",
        "Business Studies",
        "Home Economics",
        "Basic Electronics",
        "Introductory Technology",
        "Creative Practical Art",
        "Performing Art",
        "Computer Studies",
        "Music",
    ],
    "JSS 1 NAVY": [
        "Language Arts",
        "Mathematics",
        "Integrated Science",
        "Social Studies",
        "Agricultural Science",
        "Physical Health Education",
        "Religious and Moral Education",
        "French",
        "S.L Language(kerio)",
        "Business Studies",
        "Home Economics",
        "Basic Electronics",
        "Introductory Technology",
        "Creative Practical Art",
        "Performing Art",
        "Computer Studies",
        "Music",
    ],
    "JSS 1 BLUE": [
        "Language Arts",
        "Mathematics",
        "Integrated Science",
        "Social Studies",
        "Agricultural Science",
        "Physical Health Education",
        "Religious and Moral Education",
        "French",
        "S.L Language(kerio)",
        "Business Studies",
        "Home Economics",
        "Basic Electronics",
        "Introductory Technology",
        "Creative Practical Art",
        "Performing Art",
        "Computer Studies",
        "Music",
    ],

    "JSS 2 WHITE": [
        "Language Arts",
        "Mathematics",
        "Integrated Science",
        "Social Studies",
        "Agricultural Science",
        "Physical Health Education",
        "Religious and Moral Education",
        "French",
        "S.L Language(kerio)",
        "Business Studies",
        "Home Economics",
        "Basic Electronics",
        "Introductory Technology",
        "Creative Practical Art",
        "Performing Art",
        "Music",
        "Computer Studies",
    ],
    "JSS 2 NAVY": [
        "Language Arts",
        "Mathematics",
        "Integrated Science",
        "Social Studies",
        "Agricultural Science",
        "Physical Health Education",
        "Religious and Moral Education",
        "French",
        "S.L Language(kerio)",
        "Business Studies",
        "Home Economics",
        "Basic Electronics",
        "Introductory Technology",
        "Creative Practical Art",
        "Performing Art",
        "Music",
        "Computer Studies",
    ],
    "JSS 2 BLUE": [
        "Language Arts",
        "Mathematics",
        "Integrated Science",
        "Social Studies",
        "Agricultural Science",
        "Physical Health Education",
        "Religious and Moral Education",
        "French",
        "S.L Language(kerio)",
        "Business Studies",
        "Home Economics",
        "Basic Electronics",
        "Introductory Technology",
        "Creative Practical Art",
        "Performing Art",
        "Music",
        "Computer Studies",
    ],
    "JSS 2 GREY": [
        "Language Arts",
        "Mathematics",
        "Integrated Science",
        "Social Studies",
        "Agricultural Science",
        "Physical Health Education",
        "Religious and Moral Education",
        "French",
        "S.L Language(kerio)",
        "Business Studies",
        "Home Economics",
        "Basic Electronics",
        "Introductory Technology",
        "Creative Practical Art",
        "Performing Art",
        "Music",
        "Computer Studies",
    ],
    "JSS 3 GREY": [
        "Agricultural Science",
        "French",
        "Integrated Science",
        "Language Arts",
        "Mathematics",
        "Physical Health Education",
        "Religious and Moral Education",
        "S.L Language(kerio)",
        "Social Studies",
        "Home Economics",
        "Introductory Technology",
        "Business Studies",
        "Creative Practical Art",
        "Introduction To Computer",
        "Basic Electronics",
    ],
    "JSS 3 WHITE": [
         "Agricultural Science",
        "French",
        "Integrated Science",
        "Language Arts",
        "Mathematics",
        "Physical Health Education",
        "Religious and Moral Education",
        "S.L Language(kerio)",
        "Social Studies",
        "Home Economics",
        "Introductory Technology",
        "Business Studies",
        "Creative Practical Art",
        "Introduction To Computer",
        "Basic Electronics",
    ],
    "JSS 3 BLUE": [
         "Agricultural Science",
        "French",
        "Integrated Science",
        "Language Arts",
        "Mathematics",
        "Physical Health Education",
        "Religious and Moral Education",
        "S.L Language(kerio)",
        "Social Studies",
        "Home Economics",
        "Introductory Technology",
        "Business Studies",
        "Creative Practical Art",
        "Introduction To Computer",
        "Basic Electronics",
    ],
    "JSS 3 NAVY": [
        "Agricultural Science",
        "French",
        "Integrated Science",
        "Language Arts",
        "Mathematics",
        "Physical Health Education",
        "Religious and Moral Education",
        "S.L Language(kerio)",
        "Social Studies",
        "Home Economics",
        "Introductory Technology",
        "Business Studies",
        "Creative Practical Art",
        "Introduction To Computer",
        "Basic Electronics",
    ],
    "SSS 1 Blue": [
        "English Literature",
        "Government",
        "English Language",
        "C.R.S.",
        "Economics",
        "M.I.L",
        "Health Science",
        "History",
        "Geography",
        "French",
    ],

    "SSS 2 Blue": [
        // subjects...
    ],

    "SSS 3 Blue": [
        // subjects...
    ],
};

export const getCurriculumSubjects = (className) => {
  return curriculumSubjects[className] || [];
};